include:
  - board: nice_nano_v2
    shield: myshield_left
  - board: nice_nano_v2
    shield: myshield_right
    extra_cmake_args:
      -DCONFIG_CUSTOM_LINKER_SCRIPT=y
      -DCONFIG_NORDIC_QSPI_NOR=n
      -DCONFIG_BOOTLOADER_MCUBOOT=n
