name: ZMK Build

# Run on push, PR, and manually
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        side: [left, right]   # Builds both sides
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # === Install Zephyr SDK + west ===
      - name: Install toolchain
        run: |
          pip3 install --user west
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.9/zephyr-sdk-0.16.9_linux-x86_64.tar.xz
          tar xf zephyr-sdk-0.16.9_linux-x86_64.tar.xz -C $HOME
          echo "$HOME/zephyr-sdk-0.16.9/bin" >> $GITHUB_PATH

      # === Initialize west ===
      - name: West init & update
        run: |
          west init -l config
          west update
          west zephyr-export

      # === BUILD LEFT (peripheral) / RIGHT (central) ===
      - name: Build ${{ matrix.side }} side
        run: |
          SIDE=${{ matrix.side }}
          SHIELD="myshield_${SIDE}"

          # FORCE CORRECT SPLIT ROLE
          if [ "$SIDE" = "left" ]; then
            EXTRA_D="-DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_BT_CENTRAL=n -DCONFIG_BT_PERIPHERAL=y"
          else
            EXTRA_D="-DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_BT_CENTRAL=y"
          fi

          west build -b nice_nano_v2 \
            -- -DSHIELD=$SHIELD \
               -DZMK_CONFIG=$(pwd)/config \
               $EXTRA_D \
               --pristine

          # === PROOF IT WORKED ===
          echo "=== FINAL CONFIG ($SIDE) ==="
          grep -E "ZMK_SPLIT_ROLE_CENTRAL|BT_CENTRAL|BT_PERIPHERAL|ZMK_USB" build/zephyr/.config || true

          # Flash size check
          USED=$(awk '/FLASH/ {gsub(/[()]/,"",$3); print $3}' build/zephyr/zephyr.map 2>/dev/null || echo "0")
          echo "Flash used: $USED bytes"
          if [ "$USED" -gt 900000 ]; then
            echo "OVERFLOW DETECTED!"
            exit 1
          fi

          cp build/zephyr/zmk.uf2 "zmk_${SIDE}.uf2"

      # === Upload .uf2 files ===
      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: zmk-${{ matrix.side }}
          path: zmk_${{ matrix.side }}.uf2
