name: Build ZMK Firmware

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board_shield:
          - board: nice_nano
            shield: lily58_left
          - board: nice_nano
            shield: lily58_right

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install west
        run: pip install west

      - name: Initialize ZMK
        run: |
          west init -l .
          west update

      - name: Build ZMK firmware
        run: west build -s app -b ${{ matrix.board_shield.board }} -- -DSHIELD=${{ matrix.board_shield.shield }}

      - name: Convert HEX to UF2
        run: |
          python3 scripts/uf2conv.py build/zephyr/zephyr.hex -c -b 0xADA52840 -o build/zephyr/zephyr.uf2

      - name: Upload UF2
        uses: actions/upload-artifact@v3
        with:
          name: zmk-firmware-${{ matrix.board_shield.shield }}
          path: build/zephyr/zephyr.uf2
